version: '3.7'

services:
  # gameapp-redis:
  #   image: bitnami/redis:6.2
  #   container_name: gameapp-redis
  #   restart: always
  #   ports:
  #     - '6380:6379'
  #   # TODO - remove `--save "" --appendonly no` from command to persist data
  #   command: redis-server --loglevel warning --protected-mode no --save "" --appendonly no
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   volumes:
  #     - gameapp-redis-data:/data
  gameapp-database:
    image: mysql:latest
    ports:
      - "3308:3306"
    container_name: gameapp-database
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: gameappRoo7t0lk2o20
      MYSQL_DATABASE: gameapp_db
      MYSQL_USER: gameapp
      MYSQL_PASSWORD: 1234qwer


volumes:
  dbdata:
  # gameapp-redis-data: